### ISSUE TITLE
Package the app as a snap

### ISSUE THREAD

**Issue by gnarea** [relaycorp/awala-gateway-desktop#188]
I tried to do it with:

```yaml
linux:
  target:
    - AppImage
    - snap
  category: Network
  icon: src/electron/assets/logo.png
snap:
  buildPackages:
    - libc6
  stagePackages:
    - default
    - libc6
    - libappindicator1
```

But got this **runtime** error:

```
$ awala
Gtk-Message: 12:29:47.619: Failed to load module "colorreload-gtk-module"
/snap/awala/x1/app/resources/app.asar/node_modules/daemon/node_modules/grpc/src/grpc_extension.js:58
    throw e;
    ^

Error: Failed to load /snap/awala/x1/app/resources/app.asar/node_modules/daemon/node_modules/grpc/src/node/extension_binary/electron-v12.0-linux-x64-glibc/grpc_node.node. /snap/awala/x1/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /run/user/1000/snap.awala/.org.chromium.Chromium.ywNXIS)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/snap/awala/x1/app/resources/app.asar/node_modules/daemon/node_modules/grpc/src/grpc_extension.js:32:13)
    at Module._compile **(internal/modules/cjs/loader.js:1078:30)**
```
